# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Student Name
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [2]:
# 1.1 Import Packages
from pathlib import Path
import pandas as pd

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [3]:
# 1.2 Set project folders using relative paths
project_fldr = Path.cwd().parent
raw_fldr = project_fldr / 'data' / 'raw'
processed_fldr = project_fldr / 'data' / 'processed'
print(raw_fldr)
print(processed_fldr)

c:\Users\qt29\Documents\ENV700\ENV700\data\raw
c:\Users\qt29\Documents\ENV700\ENV700\data\processed

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [4]:
# 1.3 Create file path variables
rawEPA_O3_NC24 = raw_fldr / "EPAair_O3_NC2024_raw.csv"
rawEPA_O3_NC25 = raw_fldr / "EPAair_O3_NC2025_raw.csv"
rawEPA_PM25_NC24 = raw_fldr / "EPAair_PM25_NC2024_raw.csv"
rawEPA_PM25_NC25 = raw_fldr / "EPAair_PM25_NC2025_raw.csv"

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [5]:
# 1.4 Read data into dataframes

O3_NC24 = pd.read_csv(rawEPA_O3_NC24)
O3_NC25 = pd.read_csv(rawEPA_O3_NC25)
PM25_NC24 = pd.read_csv(rawEPA_PM25_NC24)
PM25_NC25 = pd.read_csv(rawEPA_PM25_NC25)

O3_NC24.head(2)
O3_NC25.head(2)
PM25_NC24.head(2)
PM25_NC25.head(2)

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,Units,Daily AQI Value,Local Site Name,Daily Obs Count,Percent Complete,...,Method Code,Method Description,CBSA Code,CBSA Name,State FIPS Code,State,County FIPS Code,County,Site Latitude,Site Longitude
0,01/01/2025,AQS,370110002,1,0.7,ug/m3 LC,4,Linville Falls,1,100.0,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
1,01/04/2025,AQS,370110002,1,1.2,ug/m3 LC,7,Linville Falls,1,100.0,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [6]:
# 1.5 Report the dimensions of each dataset
print(O3_NC24.shape)
print(O3_NC25.shape)
print(PM25_NC24.shape)
print(PM25_NC25.shape)

(9519, 21)
(9466, 21)
(9752, 22)
(10184, 22)

---
### 2. Wrangle individual datasets

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [7]:
# Convert the Date column to DateTime objects

O3_NC24["Date"] = pd.to_datetime(O3_NC24["Date"],format='%m/%d/%Y')
O3_NC25['Date'] = pd.to_datetime(O3_NC25['Date'],format='%m/%d/%Y')
PM25_NC24['Date'] = pd.to_datetime(PM25_NC24['Date'],format='%m/%d/%Y')
PM25_NC25['Date'] = pd.to_datetime(PM25_NC25['Date'],format='%m/%d/%Y')



# Print date ranges
print(f'Earliest record occurred on {O3_NC24['Date'].min()}')
print(f'Latest record occurred on {O3_NC24['Date'].max()}')

print(f'Earliest record occurred on {O3_NC25['Date'].min()}')
print(f'Latest record occurred on {O3_NC25['Date'].max()}')

Earliest record occurred on 2024-01-01 00:00:00
Latest record occurred on 2024-12-30 00:00:00
Earliest record occurred on 2025-01-01 00:00:00
Latest record occurred on 2025-12-31 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [8]:
# 2.2 Subset columns
Necessary_columns = ['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']

O3_NC24_shorten = O3_NC24[Necessary_columns]
O3_NC25_shorten = O3_NC25[Necessary_columns]
PM25_NC24_shorten = PM25_NC24[Necessary_columns]
PM25_NC25_shorten = PM25_NC25[Necessary_columns]

O3_NC24_shorten.head()

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
0,2024-03-01,26,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
1,2024-03-02,34,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
2,2024-03-03,35,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
3,2024-03-04,37,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
4,2024-03-05,42,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [9]:
# 2.3 Update values

PM25_NC24_shorten["AQS Parameter Description"] = "PM2.5"
PM25_NC25_shorten["AQS Parameter Description"] = "PM2.5"


PM25_NC25_shorten.head()

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
0,2025-01-01,4,Linville Falls,PM2.5,Avery,35.972347,-81.933072
1,2025-01-04,7,Linville Falls,PM2.5,Avery,35.972347,-81.933072
2,2025-01-07,8,Linville Falls,PM2.5,Avery,35.972347,-81.933072
3,2025-01-10,23,Linville Falls,PM2.5,Avery,35.972347,-81.933072
4,2025-01-13,28,Linville Falls,PM2.5,Avery,35.972347,-81.933072

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [10]:
# 3.1 Ensure column are same across all dataframes
print(O3_NC24_shorten.columns)
print(O3_NC25_shorten.columns)
print(PM25_NC24_shorten.columns)
print(PM25_NC25_shorten.columns)

Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [11]:
# 3.2 Concatentate & report shape
recombined_data = pd.concat([O3_NC25_shorten, O3_NC24_shorten, PM25_NC25_shorten, PM25_NC24_shorten],ignore_index=True)
recombined_data.shape

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [12]:
# 3.3 View a sample of data
recombined_data.sample(10, random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
26921,2025-10-01,43,Northampton County,PM2.5,Northampton,36.511708,-77.655389
6483,2025-03-01,50,University Meadows,Ozone,Mecklenburg,35.314158,-80.713469
34315,2024-08-31,43,Garinger High School,PM2.5,Mecklenburg,35.240100,-80.785683
12494,2024-03-30,71,Union Cross,Ozone,Forsyth,36.051805,-80.144933
27781,2025-03-08,41,Bryson City,PM2.5,Swain,35.434767,-83.442133
23089,2025-11-29,35,Clemmons Middle,PM2.5,Forsyth,36.026612,-80.341962
35024,2024-07-23,30,Friendship Park,PM2.5,Mecklenburg,35.281791,-80.851473
1157,2025-06-29,37,Beaufort,Ozone,Carteret,34.884800,-76.620300
4178,2025-07-14,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625
13592,2024-07-24,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [13]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
#sites_oz24 = set(ozone2024['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
#sites_oz25 = set(ozone2025['Local Site Name'])
#sites_pm24 = set(pm25_2024['Local Site Name'])
#sites_pm25 = set(pm25_2025['Local Site Name'])

sites_oz24 = set(O3_NC24_shorten['Local Site Name'])
sites_oz25 = set(O3_NC25_shorten['Local Site Name'])
sites_pm24 = set(PM25_NC24_shorten['Local Site Name'])
sites_pm25 = set(PM25_NC25_shorten['Local Site Name'])

## Compute the intersection 
common_sites = sites_oz24 & sites_oz25 & sites_pm24 & sites_pm25
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [14]:
# 4.1 Subset for records with sites in common
common_site_data = recombined_data.loc[
    (recombined_data["Local Site Name"].isin(common_sites))
    ]

common_site_data.shape
common_site_data.head(
    
)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
247,2025-03-01,47,Linville Falls,Ozone,Avery,35.972347,-81.933072
248,2025-03-02,43,Linville Falls,Ozone,Avery,35.972347,-81.933072
249,2025-03-03,44,Linville Falls,Ozone,Avery,35.972347,-81.933072
250,2025-03-04,44,Linville Falls,Ozone,Avery,35.972347,-81.933072
251,2025-03-05,45,Linville Falls,Ozone,Avery,35.972347,-81.933072

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [15]:
# 4.2 Group and summarize data, then report its dimensions

pollutant_summary = (
    common_site_data
    .groupby(['Date','Local Site Name','AQS Parameter Description','County'])
    .agg(
        mean_latitude = ("Site Latitude", "mean"),
        mean_longtitude = ("Site Longitude", "mean"),
        mean_AQI = ("Daily AQI Value","mean")
    )
    .reset_index()
    .sort_values(['Date','Local Site Name','AQS Parameter Description','County'])
)

pollutant_summary

,Date,Local Site Name,AQS Parameter Description,County,mean_latitude,mean_longtitude,mean_AQI
0,2024-01-01,Bryson City,PM2.5,Swain,35.434767,-83.442133,43.0
1,2024-01-01,Castle Hayne,PM2.5,New Hanover,34.364167,-77.838611,44.5
2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,36.026612,-80.341962,47.5
3,2024-01-01,Durham Armory,PM2.5,Durham,36.032955,-78.904037,61.0
4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,35.379167,-82.792500,14.0
...,...,...,...,...,...,...,...
17012,2025-12-31,Millbrook School,PM2.5,Wake,35.856111,-78.574167,24.0
17013,2025-12-31,Pitt Agri. Center,PM2.5,Pitt,35.641276,-77.360126,23.0
17014,2025-12-31,Rockwell,Ozone,Rowan,35.551868,-80.395039,35.0
17015,2025-12-31,Rockwell,PM2.5,Rowan,35.551868,-80.395039,21.0
17016,2025-12-31,West Johnston Co.,PM2.5,Johnston,35.590950,-78.462200,25.0

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [16]:
# 4.3 Calculate year and month columns

pollutant_summary_with_calculated_columns = (
    pollutant_summary
    .assign(
            year = lambda df: df['Date'].dt.year,
            month = lambda df: df['Date'].dt.month,
    )
    .reset_index()
    .sort_values(['month','year'])
)

pollutant_summary_with_calculated_columns.head()

,index,Date,Local Site Name,AQS Parameter Description,County,mean_latitude,mean_longtitude,mean_AQI,year,month
0,0,2024-01-01,Bryson City,PM2.5,Swain,35.434767,-83.442133,43.0,2024,1
1,1,2024-01-01,Castle Hayne,PM2.5,New Hanover,34.364167,-77.838611,44.5,2024,1
2,2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,36.026612,-80.341962,47.5,2024,1
3,3,2024-01-01,Durham Armory,PM2.5,Durham,36.032955,-78.904037,61.0,2024,1
4,4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,35.379167,-82.792500,14.0,2024,1

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [19]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns



season_temperature_wide = (
    pollutant_summary
    .pivot_table(
        index=['Date','Local Site Name', 'Year', 'Month', 'Site Latitude', 'Site Longitude', 'County'],
        columns='AQS Parameter Description',
        values='Daily AQI Value'
    )
    .reset_index()
)

KeyError: 'Daily AQI Value'

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [ ]:
# 5.1 Save the file

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [ ]:
# 6.1 Generate a summary table and show its first 5 records

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.